apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummy-apps-merged
resources:
- ../../../../base/dummy-apps/_template
patches:
- patch: |
    - op: add
      path: /spec/path
      value: ./overlays/lab-test/dummy-apps-merged
  target:
    kind: Kustomization
    name: "dummy-apps"
