# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
    args:
      - --maxkb=1024
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: check-yaml
    args:
    - --allow-multiple-documents
    exclude: (^infrastructure/base/|^services/base/|^tenants/base/)
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: pretty-format-json
    args: ['--autofix']
    # exclude: (^infrastructure/base/|^services/base/|^tenants/base/)
  - id: trailing-whitespace
- repo: https://github.com/k8s-at-home/sops-pre-commit
  rev: v2.0.3
  hooks:
  - id: forbid-secrets
    exclude: ^services/base/
