apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummy-apps-frontend
resources:
  - ../_template
patches:
  # Kustomization
  - patch: |
      - op: add
        path: /spec/targetNamespace
        value: dummy-apps-frontend
    target:
      kind: Kustomization
      name: "dummy-apps"
  - patch: |
      - op: add
        path: /spec/path
        value: ./base/dummy-frontend
    target:
      kind: Kustomization
      name: "dummy-apps"
  # ImageUpdateAutomation
  - patch: |
      - op: add
        path: /spec/update/path
        value: ./base/dummy-frontend
    target:
      kind: ImageUpdateAutomation
      name: "dummy-apps"
