apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummy-backend
resources:
- ../_template
patches:
- patch: |
    - op: add
      path: /spec/path
      value: ./base/dummy-backend/helm
  target:
    kind: Kustomization
    name: "dummy-apps"
