apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: restricted
    toolkit.fluxcd.io/tenant: dummy-apps
  name: dummy-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dummy-apps
  name: sa-dummy-apps
  namespace: dummy-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dummy-apps
  name: dummy-apps-reconciler
  namespace: dummy-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:dummy-apps:reconciler
- kind: ServiceAccount
  name: sa-dummy-apps
  namespace: dummy-apps
