---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dummy-apps
  namespace: dummy-apps
spec:
  interval: 10m
  ref:
    branch: main
  secretRef:
    name: dummy-apps-git-auth
  url: ssh://git@github.com/DmitriySafronov/flux2-tenant-dummy-apps.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dummy-apps
  namespace: dummy-apps
spec:
  serviceAccountName: sa-dummy-apps
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./
  sourceRef:
    kind: GitRepository
    name: dummy-apps
  interval: 5m0s
  timeout: 10m0s # give up waiting after ...
  retryInterval: 2m0s # retry every ... on apply or waiting failures
  wait: true # wait for all applied resources to become ready
  prune: true # remove stale resources from cluster
  force: false # enable this to recreate resources on immutable fields changes
