apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./tenants/overlays/lab-test
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 5m0s
  timeout: 10m0s # give up waiting after ...
  retryInterval: 2m0s # retry every ... on apply or waiting failures
  wait: true # wait for all applied resources to become ready
  prune: true # remove stale resources from cluster
  force: false # enable this to recreate resources on immutable fields changes
