apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/dummy-apps/dummy-apps-merged
patches:
- patch: |
    - op: add
      path: /spec/path
      value: ./overlays/lab/dummy-apps-merged
  target:
    kind: Kustomization
    name: "dummy-apps"
